[package]
name = "control_acks_ingestor"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "LEGENDARY Control ACKs Ingestor - Kafka to ClickHouse with hash-chain verification"

[dependencies]
# Async runtime
tokio.workspace = true

# Kafka
rdkafka.workspace = true

# ClickHouse
clickhouse.workspace = true

# Protobuf
prost.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true

# Logging and metrics
tracing.workspace = true
tracing-subscriber.workspace = true

# Utilities
futures = "0.3"
hex = "0.4"
blake3 = "1.5"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4", "serde"] }

# Configuration
config = "0.14"
dotenv = "0.15"

# HTTP server for metrics
axum = "0.7"
tower = "0.5"
tower-http = { version = "0.5", features = ["trace", "metrics"] }

[build-dependencies]
prost-build = "0.13"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false