[package]
name = "solana-historical-ingester"
version = "1.0.0"
edition = "2021"

[dependencies]
# Core async runtime
tokio = { version = "1.40", features = ["full"] }
tokio-stream = "0.1"

# gRPC and protobuf
tonic = { version = "0.12", features = ["tls", "tls-roots", "compression"] }
prost = "0.13"
prost-types = "0.13"

# Kafka producer
rdkafka = { version = "0.36", features = ["tokio", "ssl", "sasl"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
base64 = "0.22"
bs58 = "0.5"

# Yellowstone gRPC client
yellowstone-grpc-client = { version = "2.0", default-features = false, features = ["tonic-tls"] }
yellowstone-grpc-proto = { version = "2.0", default-features = false }

# Solana SDK
solana-sdk = "2.0"
solana-transaction-status = "2.0"
solana-account-decoder = "2.0"

# Monitoring and logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
prometheus = { version = "0.13", features = ["process"] }
metrics = "0.23"
metrics-exporter-prometheus = "0.15"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Configuration
config = "0.14"
clap = { version = "4.5", features = ["derive", "env"] }
dotenv = "0.15"

# Utilities
futures = "0.3"
futures-util = "0.3"
crossbeam-channel = "0.5"
parking_lot = "0.12"
dashmap = "6.0"
lru = "0.12"
backoff = { version = "0.4", features = ["tokio"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Performance optimization
jemallocator = "0.5"

[build-dependencies]
tonic-build = "0.12"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = false
strip = true
panic = "abort"

[profile.release.package."*"]
opt-level = 3

[[bin]]
name = "ingester"
path = "src/main.rs"