version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-docker
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./arbitrage-data-capture/clickhouse/ddl:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

volumes:
  clickhouse-data: