# Solana MEV Backend Configuration

rpc_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"
rpc_timeout_ms = 5000
max_concurrent_bundles = 100
bundle_timeout_ms = 50
mempool_scan_interval_ms = 10
opportunity_scan_interval_ms = 5
clickhouse_url = "http://localhost:8123"
redis_url = "redis://localhost:6379"
kafka_brokers = ["localhost:9092"]

[jito_config]
block_engine_url = "https://mainnet.block-engine.jito.wtf"
relayer_urls = [
    "https://amsterdam.mainnet.block-engine.jito.wtf",
    "https://frankfurt.mainnet.block-engine.jito.wtf",
    "https://ny.mainnet.block-engine.jito.wtf",
    "https://tokyo.mainnet.block-engine.jito.wtf"
]
auth_keypair_path = "/keys/jito-auth.json"
tip_account = "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5"
min_tip_lamports = 10000
max_tip_lamports = 1000000
bundle_timeout_ms = 5000

[quic_config]
leader_endpoints = [
    "147.28.144.67:8000",
    "147.28.144.68:8000",
    "147.28.144.69:8000",
    "147.28.144.70:8000"
]
max_concurrent_streams = 1024
initial_rtt_ms = 10
max_idle_timeout_ms = 30000
keep_alive_interval_ms = 5000
congestion_controller = "bbr"

[arbitrage_config]
min_profit_lamports = 100000
max_hops = 3
slippage_tolerance_bps = 50
simulation_compute_limit = 1400000
max_input_sol = 100.0
priority_fee_lamports = 10000

[performance_config]
cpu_affinity_mask = 255  # Use first 8 cores
memory_pool_size_mb = 2048
io_uring_enabled = true
thread_priority = 99
batch_size = 32