[package]
name = "arbitrage-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
ethnum = { workspace = true }
rust_decimal = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
clickhouse = { workspace = true }
redis = { workspace = true }
rdkafka = { workspace = true }
prometheus = { workspace = true }
tracing = { workspace = true }
rust-common = { path = "../../shared/rust-common" }
backend-shared-strategy = { path = "../../shared/strategy" }
shared-types = { path = "../../shared-types" }

[[bin]]
name = "arbitrage-engine"
path = "src/main.rs"