#!/bin/bash

echo "Docker Permission Fix Script"
echo "============================"
echo ""
echo "Docker is installed but you don't have permission to use it."
echo "Here are the steps to fix this:"
echo ""
echo "Option 1: Add your user to the docker group (recommended):"
echo "  sudo usermod -aG docker $USER"
echo "  newgrp docker"
echo ""
echo "Option 2: Run make commands with sudo:"
echo "  sudo make infra-up"
echo ""
echo "Option 3: Use rootless Docker (if available):"
echo "  dockerd-rootless-setuptool.sh install"
echo ""
echo "After fixing permissions, try running:"
echo "  make infra-up"
echo ""
echo "Current user: $USER"
echo "Docker groups: $(groups | grep -o 'docker' || echo 'not in docker group')"