# Kafka Configuration for MEV Sandwich Detector
# Separate from arbitrage topics for complete isolation

version: '3.8'

topics:
  # Raw sandwich detection events
  sandwich-raw:
    partitions: 32
    replication_factor: 1
    retention_ms: 86400000  # 1 day
    segment_ms: 3600000     # 1 hour
    compression_type: zstd
    max_message_bytes: 10485760  # 10MB
    min_insync_replicas: 1
    
  # Processed sandwich decisions
  sandwich-decisions:
    partitions: 16
    replication_factor: 1
    retention_ms: 259200000  # 3 days
    segment_ms: 7200000      # 2 hours
    compression_type: zstd
    cleanup_policy: delete
    
  # Bundle submission outcomes
  sandwich-outcomes:
    partitions: 8
    replication_factor: 1
    retention_ms: 604800000  # 7 days
    segment_ms: 14400000     # 4 hours
    compression_type: zstd
    
  # System metrics and monitoring
  sandwich-metrics:
    partitions: 4
    replication_factor: 1
    retention_ms: 172800000  # 2 days
    compression_type: snappy
    
producer_config:
  bootstrap_servers:
    - localhost:9092
  
  # Performance settings
  batch_size: 1048576        # 1MB batches
  linger_ms: 10              # 10ms linger for batching
  compression_type: zstd
  acks: 1                     # Leader ack only for speed
  buffer_memory: 134217728    # 128MB buffer
  
  # Reliability
  retries: 3
  max_in_flight_requests_per_connection: 5
  request_timeout_ms: 5000
  
consumer_config:
  bootstrap_servers:
    - localhost:9092
  
  group_id: mev-sandwich-consumer
  
  # Performance
  fetch_min_bytes: 1048576    # 1MB minimum fetch
  fetch_max_wait_ms: 100      # 100ms max wait
  max_poll_records: 10000
  
  # Offset management
  enable_auto_commit: true
  auto_commit_interval_ms: 1000
  auto_offset_reset: latest
  
  # Session management
  session_timeout_ms: 30000
  heartbeat_interval_ms: 3000
  
streams_config:
  application_id: mev-sandwich-streams
  
  # Performance
  num_stream_threads: 4
  cache_max_bytes_buffering: 134217728  # 128MB
  commit_interval_ms: 1000
  
  # State stores
  state_dir: /var/lib/kafka-streams/mev-sandwich
  
  # Processing
  processing_guarantee: at_least_once
  
connector_config:
  clickhouse_sink:
    name: sandwich-clickhouse-sink
    connector_class: io.confluent.connect.jdbc.JdbcSinkConnector
    tasks_max: 4
    topics:
      - sandwich-decisions
      - sandwich-outcomes
    connection_url: "jdbc:clickhouse://localhost:8123/mev_sandwich_db"
    connection_user: default
    auto_create: false
    batch_size: 10000
    
monitoring:
  metrics_reporters:
    - io.confluent.metrics.reporter.ConfluentMetricsReporter
  
  metric_recording_level: INFO
  
  jmx:
    enabled: true
    port: 9999
    
  prometheus:
    enabled: true
    port: 9308