[package]
name = "mev-sandwich-detector"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false
overflow-checks = false

[dependencies]
# Core async runtime - pinned threads
tokio = { version = "1.35", features = ["full", "rt-multi-thread", "parking_lot", "io-util"] }
tokio-uring = "0.4"

# Networking - zero-copy hot path
quinn = { version = "0.10", features = ["ring"] }
socket2 = { version = "0.5", features = ["all"] }
libc = "0.2"
nix = { version = "0.27", features = ["socket", "sched", "time"] }

# SIMD & Performance
packed_simd_2 = "0.3"
rayon = "1.8"
crossbeam = { version = "0.8", features = ["crossbeam-channel"] }
parking_lot = "0.12"
ahash = "0.8"
dashmap = "5.5"

# Solana & MEV
solana-sdk = "1.17"
solana-client = "1.17"
solana-transaction-status = "1.17"
solana-account-decoder = "1.17"
borsh = "1.3"
spl-token = "4.0"
spl-associated-token-account = "2.3"

# Data structures
bytes = "1.5"
smallvec = "1.11"
arrayvec = "0.7"
tinyvec = { version = "1.6", features = ["alloc"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rmp-serde = "1.1"

# Database & Caching
clickhouse-rs = { version = "1.0", features = ["tokio_io"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager", "script"] }
rdkafka = { version = "0.35", features = ["tokio"] }

# ML Inference
ort = { version = "1.16", features = ["cuda", "tensorrt"] }
ndarray = "0.15"
candle-core = { version = "0.3", features = ["cuda"] }

# Monitoring
prometheus = "0.13"
metrics = "0.21"
metrics-exporter-prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Configuration
config = "0.13"
dotenvy = "0.15"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Time & Scheduling
chrono = "0.4"
quanta = "0.12"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "mev-sandwich-detector"
path = "src/main.rs"

[lib]
name = "mev_sandwich_lib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]