# MEV Integrated Configuration
# High-performance configuration for MEV extraction and arbitrage detection

[network]
solana_rpc_url = "${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}"
jito_block_engine_url = "${JITO_BLOCK_ENGINE_URL:-https://mainnet.block-engine.jito.wtf}"
ws_url = "${SOLANA_WS_URL:-wss://api.mainnet-beta.solana.com}"

# Network optimization
max_connections = 1000
connection_timeout_ms = 1000
request_timeout_ms = 5000
retry_attempts = 3
retry_delay_ms = 100

[redis]
host = "${REDIS_HOST:-localhost}"
port = 6390
password = "${REDIS_PASSWORD:-changeme}"
max_connections = 100
connection_timeout_ms = 1000
command_timeout_ms = 500
pool_size = 50

[kafka]
brokers = "${KAFKA_BROKERS:-localhost:9092}"
producer_timeout_ms = 1000
consumer_timeout_ms = 5000
batch_size = 1000
compression_type = "lz4"
max_message_size = 10485760

# Topic configuration
[kafka.topics]
arbitrage_events = "arbitrage-events"
mev_bundles = "mev-bundles"
mempool_events = "mempool-events"
pool_updates = "pool-updates"

[clickhouse]
url = "${CLICKHOUSE_URL:-http://localhost:8123}"
database = "mev_data"
username = "default"
password = "${CLICKHOUSE_PASSWORD:-arbitrage123}"
batch_size = 10000
flush_interval_ms = 1000
max_retries = 3
connection_pool_size = 10

[arbitrage]
# Detection parameters
min_profit_threshold_sol = 0.01
max_gas_cost_sol = 0.005
confidence_threshold = 0.85
max_price_impact = 0.03
slippage_tolerance = 0.005

# Execution parameters
max_compute_units = 1400000
priority_fee_lamports = 50000
tip_percentage = 0.5
max_retry_attempts = 2

# Pool monitoring
refresh_interval_ms = 100
pool_cache_ttl_ms = 5000
max_tracked_pools = 10000

[mev]
# Bundle configuration
max_bundle_size = 5
bundle_timeout_ms = 500
tip_multiplier = 1.5
min_tip_lamports = 100000

# Submission strategies
use_jito = true
use_flashbots = false
parallel_submissions = 3
submission_delay_ms = 50

# Competition analysis
track_competitors = true
shadow_mode = false
counterfactual_analysis = true

[monitoring]
metrics_port = 9091
health_check_port = 8090
prometheus_endpoint = "/metrics"
health_endpoint = "/health"

# Metric collection intervals
metrics_interval_ms = 1000
slow_query_threshold_ms = 100
alert_threshold_profit_sol = 1.0

[performance]
# Thread pool configuration
worker_threads = 16
blocking_threads = 32
max_blocking_tasks = 1000

# Memory management
cache_size_mb = 1024
max_memory_mb = 4096
gc_interval_ms = 30000

# CPU optimization
pin_threads = true
cpu_affinity = [0, 1, 2, 3, 4, 5, 6, 7]
priority = "high"

[security]
# API keys (use environment variables in production)
jito_auth_keypair = "/keys/jito-auth.json"
api_key = "${API_KEY}"
webhook_secret = "${WEBHOOK_SECRET}"

# Rate limiting
max_requests_per_second = 1000
burst_size = 5000

# Access control
allowed_ips = ["127.0.0.1", "10.0.0.0/8"]
enable_auth = true

[logging]
level = "${RUST_LOG:-info}"
format = "json"
output = "stdout"
file_path = "/var/log/mev/mev.log"
max_file_size_mb = 100
max_files = 10
include_timestamp = true
include_thread_id = true

[alerts]
enable = true
webhook_url = "${ALERT_WEBHOOK_URL}"
email_recipients = ["${ALERT_EMAIL}"]

# Alert thresholds
high_latency_ms = 500
low_success_rate = 0.8
high_error_rate = 0.1
min_profit_alert_sol = 10.0

[advanced]
# Feature flags
enable_ml_predictions = true
enable_gas_optimization = true
enable_bundle_merging = true
enable_mempool_analysis = true

# Experimental features
use_quic_transport = false
enable_mev_boost = false
parallel_simulation = true
predictive_gas_pricing = true