[package]
name = "backend-shared-strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
redis = { version = "0.27", features = ["tokio-comp"] }
tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
anyhow = "1.0"