name: Auto Sync to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST || '45.157.234.184' }}
        username: ${{ secrets.SERVER_USER || 'kidgordones' }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: "22"
        script: |
          cd /home/kidgordones/0solana/node
          git pull origin main
          echo "✅ Code synced from GitHub"