name: Server to GitHub Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  SERVER_HOST: '45.157.234.184'
  SERVER_USER: 'kidgordones'
  SERVER_PATH: '/home/kidgordones/0solana/node'

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

    - name: Pull files from server via rsync
      run: |
        rsync -az --delete \
          -e "ssh -i ~/.ssh/deploy_key -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR" \
          ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}/ ./ \
          --exclude ".git/" \
          --exclude "node_modules/" \
          --exclude ".venv/" \
          --exclude "venv/" \
          --exclude "__pycache__/" \
          --exclude "tmp/" \
          --exclude ".cache/" \
          --exclude "*.log"

    - name: Commit and push changes
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      run: |
        git config user.name "$GIT_AUTHOR_NAME"
        git config user.email "$GIT_AUTHOR_EMAIL"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore(sync): server->GitHub $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          # Rebase to avoid conflicts
          git pull --rebase origin main || true
          git push origin HEAD:main
        fi

    - name: Cleanup
      if: always()
      run: rm -f ~/.ssh/deploy_key