[package]
name = "jito-block-engine"
version.workspace = true
edition.workspace = true

[dependencies]
tonic = { workspace = true }
solana-sdk = { workspace = true }
once_cell = { workspace = true }

[lib]
name = "jito_block_engine"
path = "src/lib.rs"


