global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'arbitrage-system'
    environment: 'production'

# Alert rules
rule_files:
  - 'alert_rules.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'arbitrage-server'

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: 
          - 'clickhouse-01:8123'
          - 'clickhouse-02:8123'
          - 'clickhouse-03:8123'
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # ClickHouse Exporter
  - job_name: 'clickhouse-exporter'
    static_configs:
      - targets: ['clickhouse-exporter:9116']

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # API Service metrics
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8080']
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: 
          - 'redis-master:6379'
          - 'redis-replica:6379'
    metrics_path: '/metrics'

  # Custom application metrics
  - job_name: 'arbitrage-app'
    static_configs:
      - targets:
          - 'data-processor:8000'
          - 'streaming-service:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

# Performance-critical metrics with higher frequency
  - job_name: 'high-frequency'
    static_configs:
      - targets:
          - 'api-service:8080'
          - 'data-processor:8000'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s