#!/bin/bash

# SECURE GitHub Authentication Setup
# This script helps you configure GitHub authentication safely

echo "🔐 Secure GitHub Authentication Setup"
echo "====================================="
echo ""
echo "⚠️  SECURITY BEST PRACTICES:"
echo "1. NEVER share your GitHub token with anyone"
echo "2. NEVER commit tokens to repositories"
echo "3. ALWAYS revoke compromised tokens immediately"
echo ""
echo "📝 To set up GitHub authentication:"
echo ""
echo "Option 1: Using Personal Access Token (Recommended)"
echo "---------------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select scopes: repo, workflow"
echo "4. Generate and copy the token"
echo "5. Run this command:"
echo ""
echo "   git remote set-url origin https://YOUR_USERNAME:YOUR_TOKEN@github.com/marcosbondrpc/solana2.git"
echo ""
echo "Option 2: Using SSH Key (More Secure)"
echo "--------------------------------------"
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C 'your-email@example.com'"
echo ""
echo "2. Add to SSH agent:"
echo "   eval \$(ssh-agent -s)"
echo "   ssh-add ~/.ssh/id_ed25519"
echo ""
echo "3. Copy public key:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo ""
echo "4. Add to GitHub: https://github.com/settings/keys"
echo ""
echo "5. Change remote to SSH:"
echo "   git remote set-url origin git@github.com:marcosbondrpc/solana2.git"
echo ""
echo "Option 3: Using GitHub CLI (Easiest)"
echo "------------------------------------"
echo "1. Install GitHub CLI:"
echo "   curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "   echo 'deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main' | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
echo "   sudo apt update && sudo apt install gh"
echo ""
echo "2. Authenticate:"
echo "   gh auth login"
echo ""
echo "3. Follow the prompts to authenticate via browser"
echo ""
echo "==============================================="
echo "⚠️  IMPORTANT: If you've already shared a token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Find the compromised token"
echo "3. Click 'Delete' immediately"
echo "4. Generate a new token"
echo "==============================================="