[package]
name = "data-scrapper"
version = "1.0.0"
edition = "2021"

[dependencies]
# Core async runtime
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }

# Solana SDK
solana-sdk = { workspace = true }
solana-client = { workspace = true }
solana-transaction-status = { workspace = true }
solana-account-decoder = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }

# High-performance data structures
bytes = { workspace = true }
dashmap = { workspace = true }
crossbeam = { workspace = true }
parking_lot = { workspace = true }
arc-swap = { workspace = true }

# Database
clickhouse = { workspace = true }
redis = { workspace = true }

# Message streaming
rdkafka = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
async-stream = { workspace = true }

# Data formats
parquet = "53"
arrow = "53"
csv = "1.3"

# Compression
zstd = "0.13"
lz4 = "1.28"
snap = "1.1"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }

# ML integration
ort = { workspace = true }
ndarray = "0.16"
polars = { version = "0.44", features = ["lazy", "parquet", "csv", "json", "streaming"] }

# Web server
axum = "0.7"
tower = { workspace = true }
tower-http = { version = "0.6", features = ["cors", "compression-br", "trace"] }

# Metrics
prometheus = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Utilities
chrono = { workspace = true }
uuid = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.14"