[package]
name = "ml-inference"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ort = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prometheus = { workspace = true }
tracing = { workspace = true }
rust-common = { path = "../../shared/rust-common" }

[[bin]]
name = "ml-inference"
path = "src/main.rs"